Qo2/urls.py
from django.contrib import admin
from django.urls import path, include

from pari import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('match/', include('pari.urls', 'match'))
]

pari/urls.py
from django.urls import path
from . import views

app_name = 'match'

urlpatterns = [
    path('', views.listing, name="listing"),
]

pari/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class League(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Team(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=200)
    emblem = models.URLField(max_length=200)
    league = models.ForeignKey(League, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Match(models.Model):
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="home")
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="away")
    home_score = models.PositiveIntegerField(null=True)
    away_score = models.PositiveIntegerField(null=True)
    date_match = models.DateField()
    time_match = models.TimeField()
    decision = models.SmallIntegerField(null=True)


class User(AbstractUser):
    solde = models.PositiveIntegerField(default=0)


class Pari(models.Model):
    date_pari = models.DateTimeField(auto_now_add=True)
    somme = models.PositiveIntegerField()
    decision = models.SmallIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_pari")

pari/views.py
from django.shortcuts import render
from .models import League, Team, Match, Pari, User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import datetime
import requests


# Create your views here.
def initialise_db():
    league = League.objects.filter(id=4328)
    if not league.exists():
        response = requests.get("https://www.thesportsdb.com/api/v1/json/1/all_leagues.php")
        league = response.json()
        leagues = league['leagues']
        for element in leagues:
            if element['strLeague'] == 'English Premier League':
                league = League.objects.create(id=element['idLeague'], name=element['strLeague'])
                break
    else:
        league = league[0]
    teams = Team.objects.filter(league__id=4328)
    if not teams.exists():
        response = requests.get("https://www.thesportsdb.com/api/v1/json/1/lookup_all_teams.php?id=4328")
        teams = response.json()
        teams = teams['teams']
        for element in teams:
            if element['idLeague'] == '4328':
                teams = Team.objects.create(
                    id=element['idTeam'],
                    name=element['strTeam'],
                    emblem=element['strTeamBadge'],
                    league=league
                )
    matchs = Match.objects.all()
    if not matchs.exists():
        response = requests.get("https://www.thesportsdb.com/api/v1/json/1/eventsseason.php?id=4328&s=1920")
        matchs = response.json()
        matchs = matchs['events']
        for element in matchs:
            if element['idLeague'] == '4328':
                da = element['strDate'].split("/")
                aux = ["20" + da[2], da[1], da[0]]
                da = "-".join(aux)
                match = Match.objects.create(
                    id=element['idEvent'],
                    home_team_id=element['idHomeTeam'],
                    away_team_id=element['idAwayTeam'],
                    date_match=da,
                    time_match=element['strTime'],
                )


def index(request):
    initialise_db()
    old_ma = Match.objects.filter(date_match__lt=datetime.date.today()).order_by('-date_match')[:4]
    next_ma = Match.objects.filter(date_match__gt=datetime.date.today()).order_by('date_match')[:4]
    today_ma = Match.objects.filter(date_match=datetime.date.today()).order_by('time_match')[:4]
    context = {
        'old_ma' : old_ma,
        'today_ma': today_ma,
        'next_ma': next_ma
    }
    return render(request, 'pari/index.html', context)


def listing(request):
    ma_list = Match.objects.all().order_by('date_match')
    paginator = Paginator(ma_list, 4)
    page = request.GET.get('page')
    try:
        matchs = paginator.page(page)
    except PageNotAnInteger:
        matchs = paginator.page(1)
    except EmptyPage:
        matchs = paginator.page(paginator.num_pages)
    context = {
        'matchs':matchs,
        'paginate': True
    }
    return render(request, 'pari/listing.html', context)

pari/templates/pari/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
    {% load static %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-light fixed-top">
  <a class="navbar-brand" href="{% url 'index' %}">Qo2</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'match:listing' %}">Calendrier</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      <li class="nav-item">
        <button class="btn btn-sm align-middle btn-outline-primary" type="button">inscription</button>
      </li>
        <li class="nav-item">
        <button class="btn btn-sm align-middle btn-outline-light" type="button">connexion</button>
      </li>
    </ul>
  </div>
</nav>
<!--/.Navbar -->

  <!-- Start your project here-->
  {% block content %}{% endblock %}
  <!-- Start your project here-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

pari/templates/pari/index.html
{% extends 'pari/base.html' %}

{% block content %}
    {% load static %}
     <!--Section: Jumbotron-->
      <section class="card wow fadeIn mb-3" style="background-image: url({% static 'téléchargement.png' %});">

        <!-- Content -->
        <div class="card-body text-white text-center py-5 px-5 my-5">

          <h1 class="mb-4">
            <strong>Binvenue sur Qo2</strong>
          </h1>
          <p>
            <strong>Le meilleur site de pari pour la première ligue</strong>
          </p>
          <p class="mb-4">
            <strong>Ici, pas de quote variante, c'est toujours quitte ou double.</strong>
          </p>
          <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">S'inscrire
            <i class="fas fa-graduation-cap ml-2"></i>
          </a>

        </div>
        <!-- Content -->
      </section>
      <!--Section: Jumbotron-->
    <div class="container-fluid text-center mt-5">
        <h3>Matches récents</h3>
        <!-- Card deck -->
        <div class="card-deck">
        {% for match in old_ma %}
          <!-- Card -->
          <div class="card mb-3">

            <!--Card image-->
            <div class="view overlay">
              <img class="card-img-top" src="{{ match.home_team.emblem }}" alt="Card image cap">
              <a href="#!">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <!--Card content-->
            <div class="card-body">

              <!--Title-->
              <h4 class="card-title">{{ match.home_team.name }} : {{ match.home_score }} - {{ match.away_score }} : {{ match.away_team.name }}</h4>
              <!--Text-->
              <p class="card-text">Date: {{ match.date_match }}<br>Heure: {{ match.time_match }}</p>
            </div>

          </div>
          <!-- Card -->
        {% endfor %}
        </div>
        <!-- Card deck -->
    </div>
    <div class="container-fluid text-center mt-5">
        <h3>Matches Aujourd'hui</h3>
        <!-- Card deck -->
        <div class="card-deck">
        {% for match in today_ma %}
          <!-- Card -->
          <div class="card mb-3">

            <!--Card image-->
            <div class="view overlay">
              <img class="card-img-top" src="{{ match.home_team.emblem }}" alt="Card image cap">
              <a href="#!">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <!--Card content-->
            <div class="card-body">

              <!--Title-->
              <h4 class="card-title">{{ match.home_team.name }} : {{ match.home_score }} - {{ match.away_score }} : {{ match.away_team.name }}</h4>
              <!--Text-->
              <p class="card-text">Date: {{ match.date_match }}<br>lieu: {{ match.time_match }}</p>
              <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
              <button type="button" class="btn btn-light-blue btn-md">Read more</button>

            </div>

          </div>
          <!-- Card -->
        {% endfor %}
        </div>
        <!-- Card deck -->
    </div>
    <div class="container-fluid text-center mt-5">
        <h3>Matches à venir</h3>
        <!-- Card deck -->
        <div class="card-deck">
        {% for match in next_ma %}
          <!-- Card -->
          <div class="card mb-3">

            <!--Card image-->
            <div class="view overlay">
              <img class="card-img-top" src="{{ match.home_team.emblem }}" alt="Card image cap">
              <a href="#!">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <!--Card content-->
            <div class="card-body">

              <!--Title-->
              <h4 class="card-title">{{ match.home_team.name }} : {{ match.home_score }} - {{ match.away_score }} : {{ match.away_team.name }}</h4>
              <!--Text-->
              <p class="card-text">Date: {{ match.date_match }}<br>Heure: {{ match.time_match }}</p>
              <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
              <button type="button" class="btn btn-light-blue btn-md">Parier</button>

            </div>

          </div>
          <!-- Card -->
        {% endfor %}
        </div>
        <!-- Card deck -->
    </div>
{% endblock %}

pari/templates/pari/listing.html
{% extends 'pari/base.html' %}

{% block content %}
    <div class="container-fluid text-center mt-5">
        <h3>Saison</h3>
        <!-- Card deck -->
        <div class="card-deck">
        {% for match in matchs %}
          <!-- Card -->
          <div class="card mb-3">

            <!--Card image-->
            <div class="view overlay">
              <img class="card-img-top" src="{{ match.home_team.emblem }}" alt="Card image cap">
              <a href="#!">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <!--Card content-->
            <div class="card-body">

              <!--Title-->
              <h4 class="card-title">{{ match.home_team.name }} : {{ match.home_score }} - {{ match.away_score }} : {{ match.away_team.name }}</h4>
              <!--Text-->
              <p class="card-text">Date: {{ match.date_match }}<br>Heure: {{ match.time_match }}</p>
              <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
              <button type="button" class="btn btn-light-blue btn-md">Parier</button>

            </div>

          </div>
          <!-- Card -->
        {% endfor %}
        </div>
        <!-- Card deck -->
    </div>

    {% if paginate %}
        <div class="clearfix"></div>
        <nav aria-label="">
            <ul class="pager">
                {% if matchs.has_previous %}
                    <li><a href="?page={{ matchs.previous_page_number }}">Précédent</a></li>
                {% endif %}
                {% if matchs.has_next %}
                    <li><a href="?page={{ matchs.next_page_number }}">Suivant</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}